//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject {
	
	
	public partial class CrudAlimentos {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.TextBox txtDescripcion;
		
		protected System.Web.UI.WebControls.TextBox txtPrecio;
		
		protected System.Web.UI.WebControls.Button btnGuardar;
		
		protected System.Web.UI.WebControls.TextBox txtIdActualizar;
		
		protected System.Web.UI.WebControls.TextBox txtNombreActualizar;
		
		protected System.Web.UI.WebControls.TextBox txtDescripcionActualizar;
		
		protected System.Web.UI.WebControls.TextBox txtPrecioActualizar;
		
		protected System.Web.UI.WebControls.Button btnActualizar;
		
		protected System.Web.UI.WebControls.TextBox lblIdEliminar;
		
		protected System.Web.UI.WebControls.TextBox lblNombreEliminar;
		
		protected System.Web.UI.WebControls.TextBox lblDescripcionEliminar;
		
		protected System.Web.UI.WebControls.TextBox lblPrecioEliminar;
		
		protected System.Web.UI.WebControls.Button btnEliminar;
	}
}
