//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject {
    
    
    public partial class Login {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox txtUsername;
        
        protected System.Web.UI.WebControls.TextBox txtPassword;
        
        protected System.Web.UI.WebControls.Button btnLogin;
    }
}
