//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject {
	
	
	public partial class Venta {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtIdUser;
		
		protected System.Web.UI.WebControls.Button btnBuscarUsuario;
		
		protected System.Web.UI.WebControls.TextBox txtNombreUser;
		
		protected System.Web.UI.WebControls.TextBox txtIdAlimento;
		
		protected System.Web.UI.WebControls.Button btnBuscarAlimento;
		
		protected System.Web.UI.WebControls.TextBox txtNombreAlimento;
		
		protected System.Web.UI.WebControls.TextBox txtPrecioAlimento;
		
		protected System.Web.UI.WebControls.TextBox txtCantidad;
		
		protected System.Web.UI.WebControls.Button btnAgregar;
		
		protected System.Web.UI.WebControls.Literal tablaProductosLiteral;
		
		protected System.Web.UI.WebControls.Button btnVenta;
	}
}
