//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject.localhost {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DetalleVentasServicesSoap", Namespace="http://tempuri.org/")]
    public partial class DetalleVentasServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearDetalleVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDetalleVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDetalleVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarDetalleVentaOperationCompleted;
        
        /// <remarks/>
        public DetalleVentasServices() {
            this.Url = "http://localhost:8081/DetalleVentasServices.asmx";
        }
        
        public DetalleVentasServices(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event CrearDetalleVentaCompletedEventHandler CrearDetalleVentaCompleted;
        
        /// <remarks/>
        public event ObtenerDetalleVentasCompletedEventHandler ObtenerDetalleVentasCompleted;
        
        /// <remarks/>
        public event ActualizarDetalleVentaCompletedEventHandler ActualizarDetalleVentaCompleted;
        
        /// <remarks/>
        public event BorrarDetalleVentaCompletedEventHandler BorrarDetalleVentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearDetalleVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearDetalleVenta(int idVenta, int idAlimento, int cantidad, float precioUnitario) {
            object[] results = this.Invoke("CrearDetalleVenta", new object[] {
                        idVenta,
                        idAlimento,
                        cantidad,
                        precioUnitario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearDetalleVentaAsync(int idVenta, int idAlimento, int cantidad, float precioUnitario) {
            this.CrearDetalleVentaAsync(idVenta, idAlimento, cantidad, precioUnitario, null);
        }
        
        /// <remarks/>
        public void CrearDetalleVentaAsync(int idVenta, int idAlimento, int cantidad, float precioUnitario, object userState) {
            if ((this.CrearDetalleVentaOperationCompleted == null)) {
                this.CrearDetalleVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearDetalleVentaOperationCompleted);
            }
            this.InvokeAsync("CrearDetalleVenta", new object[] {
                        idVenta,
                        idAlimento,
                        cantidad,
                        precioUnitario}, this.CrearDetalleVentaOperationCompleted, userState);
        }
        
        private void OnCrearDetalleVentaOperationCompleted(object arg) {
            if ((this.CrearDetalleVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearDetalleVentaCompleted(this, new CrearDetalleVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDetalleVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerDetalleVentas() {
            object[] results = this.Invoke("ObtenerDetalleVentas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDetalleVentasAsync() {
            this.ObtenerDetalleVentasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerDetalleVentasAsync(object userState) {
            if ((this.ObtenerDetalleVentasOperationCompleted == null)) {
                this.ObtenerDetalleVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDetalleVentasOperationCompleted);
            }
            this.InvokeAsync("ObtenerDetalleVentas", new object[0], this.ObtenerDetalleVentasOperationCompleted, userState);
        }
        
        private void OnObtenerDetalleVentasOperationCompleted(object arg) {
            if ((this.ObtenerDetalleVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDetalleVentasCompleted(this, new ObtenerDetalleVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDetalleVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActualizarDetalleVenta(int id, int idVenta, int idAlimento, int cantidad, float precioUnitario) {
            object[] results = this.Invoke("ActualizarDetalleVenta", new object[] {
                        id,
                        idVenta,
                        idAlimento,
                        cantidad,
                        precioUnitario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarDetalleVentaAsync(int id, int idVenta, int idAlimento, int cantidad, float precioUnitario) {
            this.ActualizarDetalleVentaAsync(id, idVenta, idAlimento, cantidad, precioUnitario, null);
        }
        
        /// <remarks/>
        public void ActualizarDetalleVentaAsync(int id, int idVenta, int idAlimento, int cantidad, float precioUnitario, object userState) {
            if ((this.ActualizarDetalleVentaOperationCompleted == null)) {
                this.ActualizarDetalleVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDetalleVentaOperationCompleted);
            }
            this.InvokeAsync("ActualizarDetalleVenta", new object[] {
                        id,
                        idVenta,
                        idAlimento,
                        cantidad,
                        precioUnitario}, this.ActualizarDetalleVentaOperationCompleted, userState);
        }
        
        private void OnActualizarDetalleVentaOperationCompleted(object arg) {
            if ((this.ActualizarDetalleVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDetalleVentaCompleted(this, new ActualizarDetalleVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarDetalleVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BorrarDetalleVenta(int id) {
            object[] results = this.Invoke("BorrarDetalleVenta", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarDetalleVentaAsync(int id) {
            this.BorrarDetalleVentaAsync(id, null);
        }
        
        /// <remarks/>
        public void BorrarDetalleVentaAsync(int id, object userState) {
            if ((this.BorrarDetalleVentaOperationCompleted == null)) {
                this.BorrarDetalleVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarDetalleVentaOperationCompleted);
            }
            this.InvokeAsync("BorrarDetalleVenta", new object[] {
                        id}, this.BorrarDetalleVentaOperationCompleted, userState);
        }
        
        private void OnBorrarDetalleVentaOperationCompleted(object arg) {
            if ((this.BorrarDetalleVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarDetalleVentaCompleted(this, new BorrarDetalleVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void CrearDetalleVentaCompletedEventHandler(object sender, CrearDetalleVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearDetalleVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearDetalleVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ObtenerDetalleVentasCompletedEventHandler(object sender, ObtenerDetalleVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDetalleVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDetalleVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ActualizarDetalleVentaCompletedEventHandler(object sender, ActualizarDetalleVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDetalleVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDetalleVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void BorrarDetalleVentaCompletedEventHandler(object sender, BorrarDetalleVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarDetalleVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarDetalleVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
