//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject.VentasServices {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VentasServicesSoap", Namespace="http://tempuri.org/")]
    public partial class VentasServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarVentaOperationCompleted;
        
        /// <remarks/>
        public VentasServices() {
            this.Url = "http://localhost:8081/VentasServices.asmx";
        }
        
        public VentasServices(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event CrearVentaCompletedEventHandler CrearVentaCompleted;
        
        /// <remarks/>
        public event ObtenerVentasCompletedEventHandler ObtenerVentasCompleted;
        
        /// <remarks/>
        public event ActualizarVentaCompletedEventHandler ActualizarVentaCompleted;
        
        /// <remarks/>
        public event BorrarVentaCompletedEventHandler BorrarVentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearVenta(System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado) {
            object[] results = this.Invoke("CrearVenta", new object[] {
                        fechaVenta,
                        monto,
                        idCliente,
                        idEmpleado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearVentaAsync(System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado) {
            this.CrearVentaAsync(fechaVenta, monto, idCliente, idEmpleado, null);
        }
        
        /// <remarks/>
        public void CrearVentaAsync(System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado, object userState) {
            if ((this.CrearVentaOperationCompleted == null)) {
                this.CrearVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearVentaOperationCompleted);
            }
            this.InvokeAsync("CrearVenta", new object[] {
                        fechaVenta,
                        monto,
                        idCliente,
                        idEmpleado}, this.CrearVentaOperationCompleted, userState);
        }
        
        private void OnCrearVentaOperationCompleted(object arg) {
            if ((this.CrearVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearVentaCompleted(this, new CrearVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerVentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerVentas() {
            object[] results = this.Invoke("ObtenerVentas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerVentasAsync() {
            this.ObtenerVentasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerVentasAsync(object userState) {
            if ((this.ObtenerVentasOperationCompleted == null)) {
                this.ObtenerVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerVentasOperationCompleted);
            }
            this.InvokeAsync("ObtenerVentas", new object[0], this.ObtenerVentasOperationCompleted, userState);
        }
        
        private void OnObtenerVentasOperationCompleted(object arg) {
            if ((this.ObtenerVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerVentasCompleted(this, new ObtenerVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActualizarVenta(int id, System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado) {
            object[] results = this.Invoke("ActualizarVenta", new object[] {
                        id,
                        fechaVenta,
                        monto,
                        idCliente,
                        idEmpleado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarVentaAsync(int id, System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado) {
            this.ActualizarVentaAsync(id, fechaVenta, monto, idCliente, idEmpleado, null);
        }
        
        /// <remarks/>
        public void ActualizarVentaAsync(int id, System.DateTime fechaVenta, float monto, int idCliente, int idEmpleado, object userState) {
            if ((this.ActualizarVentaOperationCompleted == null)) {
                this.ActualizarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarVentaOperationCompleted);
            }
            this.InvokeAsync("ActualizarVenta", new object[] {
                        id,
                        fechaVenta,
                        monto,
                        idCliente,
                        idEmpleado}, this.ActualizarVentaOperationCompleted, userState);
        }
        
        private void OnActualizarVentaOperationCompleted(object arg) {
            if ((this.ActualizarVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarVentaCompleted(this, new ActualizarVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BorrarVenta(int id) {
            object[] results = this.Invoke("BorrarVenta", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarVentaAsync(int id) {
            this.BorrarVentaAsync(id, null);
        }
        
        /// <remarks/>
        public void BorrarVentaAsync(int id, object userState) {
            if ((this.BorrarVentaOperationCompleted == null)) {
                this.BorrarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarVentaOperationCompleted);
            }
            this.InvokeAsync("BorrarVenta", new object[] {
                        id}, this.BorrarVentaOperationCompleted, userState);
        }
        
        private void OnBorrarVentaOperationCompleted(object arg) {
            if ((this.BorrarVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarVentaCompleted(this, new BorrarVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void CrearVentaCompletedEventHandler(object sender, CrearVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ObtenerVentasCompletedEventHandler(object sender, ObtenerVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ActualizarVentaCompletedEventHandler(object sender, ActualizarVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void BorrarVentaCompletedEventHandler(object sender, BorrarVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
