//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodProject.LoginServices {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginServicesSoap", Namespace="http://tempuri.org/")]
    public partial class LoginServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificarCredencialesWebServiceOperationCompleted;
        
        /// <remarks/>
        public LoginServices() {
            this.Url = "http://localhost:8081/LoginServices.asmx";
        }
        
        public LoginServices(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event VerificarCredencialesWebServiceCompletedEventHandler VerificarCredencialesWebServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarCredencialesWebService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificarCredencialesWebService(string nombreUsuario, string contraseña) {
            object[] results = this.Invoke("VerificarCredencialesWebService", new object[] {
                        nombreUsuario,
                        contraseña});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarCredencialesWebServiceAsync(string nombreUsuario, string contraseña) {
            this.VerificarCredencialesWebServiceAsync(nombreUsuario, contraseña, null);
        }
        
        /// <remarks/>
        public void VerificarCredencialesWebServiceAsync(string nombreUsuario, string contraseña, object userState) {
            if ((this.VerificarCredencialesWebServiceOperationCompleted == null)) {
                this.VerificarCredencialesWebServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarCredencialesWebServiceOperationCompleted);
            }
            this.InvokeAsync("VerificarCredencialesWebService", new object[] {
                        nombreUsuario,
                        contraseña}, this.VerificarCredencialesWebServiceOperationCompleted, userState);
        }
        
        private void OnVerificarCredencialesWebServiceOperationCompleted(object arg) {
            if ((this.VerificarCredencialesWebServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarCredencialesWebServiceCompleted(this, new VerificarCredencialesWebServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void VerificarCredencialesWebServiceCompletedEventHandler(object sender, VerificarCredencialesWebServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarCredencialesWebServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarCredencialesWebServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
